[versions]
tide = "3.8"
bindables = "2.2"

[libraries]
tide = { group = "io.github.dockyardmc", name = "tide", version.ref = "tide" }
bindables = { group = "cz.lukynka", name = "kotlin-bindables", version.ref = "bindables" }
